### ISSUE TITLE
Documentation Link not working

### ISSUE THREAD

**Issue by 10corp** [centralnicgroup-opensource/rtldev-middleware-php-sdk#43]
https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/sdks/php-sdk/

**Comment by AsifNawaz-cnic** [comment]
Hi @10corp,

We appreciate you bringing the issue with the link to our public documentation on the repository level to our attention. We're excited to inform you that we have successfully resolved the problem and everything is working fine now. Thank you for your help!
